# Generated by Django 3.1.7 on 2021-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=16)),
                ('alpha', models.DecimalField(decimal_places=4, max_digits=10)),
                ('theta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('beta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_cost', models.IntegerField()),
                ('max_cost', models.IntegerField()),
            ],
        ),
    ]
