# Generated by Django 3.2.8 on 2022-01-12 18:56

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('product_name_singular', models.CharField(max_length=30)),
                ('product_name_plural', models.CharField(max_length=30)),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('theta', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gamma', models.DecimalField(decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_slope', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('accum_cost_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('endless', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('allow_robots', models.BooleanField(default=False)),
                ('monitor_auto_pilot', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('game_over', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.CreateModel(
            name='UnusedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('prod_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('round_joined', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('auto_play', models.BooleanField(default=False)),
                ('removed_from_market', models.BooleanField(default=False)),
                ('bankrupt', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('unit_amount', models.IntegerField(null=True)),
                ('round', models.IntegerField()),
                ('was_forced', models.BooleanField(default=False)),
                ('demand', models.IntegerField(null=True)),
                ('units_sold', models.IntegerField(null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.trader')),
            ],
        ),
        migrations.CreateModel(
            name='RoundStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usedcosts',
            constraint=models.UniqueConstraint(fields=('market', 'cost'), name='market_and_used_cost_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='unusedcosts',
            constraint=models.UniqueConstraint(fields=('market', 'cost'), name='market_and_unused_cost_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('market', 'name'), name='market_and_name_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('trader', 'round'), name='trader_and_round_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='roundstat',
            constraint=models.UniqueConstraint(fields=('market', 'round'), name='market_and_round_unique_together'),
        ),
    ]
