# Generated by Django 3.2.8 on 2021-10-27 08:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='alpha',
            field=models.DecimalField(decimal_places=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='beta',
            field=models.DecimalField(decimal_places=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='theta',
            field=models.DecimalField(decimal_places=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
