# Generated by Django 3.1.7 on 2021-04-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trader_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='round_amount',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='round_price',
        ),
        migrations.AddField(
            model_name='market',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(default=0)),
                ('unit_amount', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.trader')),
            ],
        ),
    ]
