# Generated by Django 3.2.8 on 2021-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20211027_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_name_plural',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_singular',
            field=models.CharField(max_length=30),
        ),
    ]
