# Generated by Django 3.1.7 on 2021-04-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210401_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='round_cost',
            field=models.IntegerField(default=0),
        ),
    ]
