# Generated by Django 3.2.8 on 2021-10-27 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20211027_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='cost_add',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
