# Generated by Django 3.2.8 on 2021-10-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_cost_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='cost_add',
            new_name='cost_slope',
        ),
    ]
