# Generated by Django 3.2.8 on 2021-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_rename_cost_add_market_cost_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='prod_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
