# Generated by Django 3.2.8 on 2021-10-27 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_trade_prod_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='total_prod_cost_change',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
