# Generated by Django 3.1.11 on 2021-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20210520_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='alpha',
            field=models.DecimalField(decimal_places=4, default=105, max_digits=10),
        ),
        migrations.AlterField(
            model_name='market',
            name='beta',
            field=models.DecimalField(decimal_places=4, default=17.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='market',
            name='max_cost',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='market',
            name='min_cost',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='market',
            name='theta',
            field=models.DecimalField(decimal_places=4, default=14.58, max_digits=10),
        ),
    ]
