# Generated by Django 3.2.8 on 2021-10-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_market_total_prod_cost_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='total_prod_cost_change',
            new_name='accum_cost_change',
        ),
    ]
