# Generated by Django 3.1.11 on 2021-05-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210521_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='bank',
            new_name='balance',
        ),
    ]
