# Generated by Django 3.1.11 on 2021-05-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20210527_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='money',
            new_name='balance',
        ),
    ]
