# Generated by Django 3.1.11 on 2021-05-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20210527_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='was_forced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.market'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='round',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.IntegerField(blank=True, default=5000),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
