# Generated by Django 3.1.11 on 2021-05-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20210529_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='unit_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
