# Generated by Django 3.2.8 on 2021-11-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_market_gamma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='beta',
        ),
    ]
