# Generated by Django 3.1.11 on 2021-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20210531_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='market',
        ),
        migrations.AlterField(
            model_name='trade',
            name='round',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='name',
            field=models.CharField(default='John Doe', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('trader', 'round'), name='trader_and_round_unique'),
        ),
    ]
