# Generated by Django 3.1.11 on 2021-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20210601_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='name',
            field=models.CharField(default='John Doe', max_length=16),
        ),
    ]
