# Generated by Django 3.1.11 on 2021-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_auto_20210603_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='round',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trader',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
