# Generated by Django 3.1.11 on 2021-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20210603_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='unit_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
