# Generated by Django 3.1.11 on 2021-06-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20210603_1610'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='trader_and_round_unique',
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('trader', 'round'), name='trader_and_round_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='trader',
            constraint=models.UniqueConstraint(fields=('market', 'name'), name='market_and_name_unique_together'),
        ),
    ]
