# Generated by Django 3.1.11 on 2021-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_auto_20210604_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
