# Generated by Django 3.1.11 on 2021-06-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_auto_20210604_1010'),
        ('market', '0024_auto_20210604_1004'),
    ]

    operations = [
    ]
