# Generated by Django 3.1.11 on 2021-06-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_auto_20210605_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('avg_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roundstat',
            constraint=models.UniqueConstraint(fields=('market', 'round'), name='market_and_round_unique_together'),
        ),
    ]
