# Generated by Django 3.1.11 on 2021-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20210605_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundstat',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
