# Generated by Django 3.1.11 on 2021-06-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_trade_num_sold_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='num_sold_unit',
            new_name='units_sold',
        ),
    ]
