# Generated by Django 3.1.11 on 2021-06-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_auto_20210606_1219'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='trader_and_round_unique_together',
        ),
    ]
