# Generated by Django 3.1.11 on 2021-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_auto_20210608_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='demand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roundstat',
            name='round',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='round',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='units_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
