# Generated by Django 3.2.4 on 2021-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0036_market_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='initial_balance',
            field=models.PositiveIntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='product_name',
            field=models.CharField(default='abe', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='alpha',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='market',
            name='beta',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='market',
            name='max_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='min_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='theta',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
