# Generated by Django 3.2.4 on 2021-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0037_auto_20210622_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.IntegerField(blank=True),
        ),
    ]
