# Generated by Django 3.2.4 on 2021-06-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0039_auto_20210623_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='product_name',
        ),
    ]
