# Generated by Django 3.2.4 on 2021-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_remove_market_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_name_plural',
            field=models.CharField(default='default_plural', max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_singular',
            field=models.CharField(default='default_singular', max_length=16),
        ),
    ]
