# Generated by Django 3.2.4 on 2021-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_auto_20210623_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
