# Generated by Django 3.2.4 on 2021-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_auto_20210623_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='endless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='max_rounds',
            field=models.IntegerField(default=15),
        ),
    ]
