# Generated by Django 3.2.4 on 2021-06-26 12:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_alter_market_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='alpha',
            field=models.DecimalField(decimal_places=4, help_text="How big should the demand for a trader's product be, if all traders set the price to zero?", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='beta',
            field=models.DecimalField(decimal_places=4, help_text="How much should the demand for a trader's product decrease, when (s)he raises the unit price by one?", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, help_text='How much money should the participants start out with?', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, help_text='What are the maximal production costs for one unit of the product?', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, help_text='What are the minimal production costs for one unit of the product?', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_plural',
            field=models.CharField(default='default_plural', help_text="The plural form of the product being sold (eg. 'baguettes')", max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_singular',
            field=models.CharField(default='default_singular', help_text="The singular form of the product being sold (e.g. 'baguette')", max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='theta',
            field=models.DecimalField(decimal_places=4, help_text="How much should the demand for a trader's product increase, when the market's average price goes up by one?", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='trader',
            name='prod_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
