# Generated by Django 3.2.4 on 2021-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_auto_20210629_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
