# Generated by Django 3.2.4 on 2021-06-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_auto_20210626_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
    ]
