# Generated by Django 3.2.4 on 2021-07-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_market_game_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='endless',
        ),
        migrations.RemoveField(
            model_name='market',
            name='game_over',
        ),
        migrations.RemoveField(
            model_name='market',
            name='max_rounds',
        ),
    ]
