# Generated by Django 3.2.4 on 2021-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_auto_20210626_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundstat',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
