# Generated by Django 3.2.4 on 2021-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0047_auto_20210627_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
