# Generated by Django 3.2.4 on 2021-06-27 09:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_alter_trade_balance_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='alpha',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='beta',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='market',
            name='max_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='min_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_plural',
            field=models.CharField(default='default_plural', max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_singular',
            field=models.CharField(default='default_singular', max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='theta',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
