# Generated by Django 3.2.4 on 2021-06-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0050_alter_trader_prod_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='unit_amount',
            field=models.IntegerField(null=True),
        ),
    ]
