# Generated by Django 3.2.4 on 2021-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_alter_trade_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
