# Generated by Django 3.2.4 on 2021-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_alter_trade_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='product_name_plural',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_name_singular',
            field=models.CharField(max_length=16),
        ),
    ]
