# Generated by Django 3.2.4 on 2021-06-30 12:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0054_auto_20210630_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='demand',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='units_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trader',
            name='prod_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
