# Generated by Django 3.2.4 on 2021-06-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0055_auto_20210630_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundstat',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
