# Generated by Django 3.2.4 on 2021-07-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0056_auto_20210630_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
