# Generated by Django 3.2.4 on 2021-08-15 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_alter_trader_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.CreateModel(
            name='UnusedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usedcosts',
            constraint=models.UniqueConstraint(fields=('market', 'cost'), name='market_and_used_cost_unique_together'),
        ),
        migrations.AddConstraint(
            model_name='unusedcosts',
            constraint=models.UniqueConstraint(fields=('market', 'cost'), name='market_and_unused_cost_unique_together'),
        ),
    ]
