# Generated by Django 3.2.4 on 2021-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0057_alter_trader_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='endless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='market',
            name='max_rounds',
            field=models.IntegerField(default=15),
        ),
    ]
