# Generated by Django 3.2.4 on 2021-08-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0063_alter_market_max_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='endless',
            field=models.BooleanField(),
        ),
    ]
