# Generated by Django 3.2.4 on 2021-08-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0064_alter_market_endless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='game_over',
        ),
    ]
