# Generated by Django 3.2.4 on 2021-08-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0067_auto_20210826_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundstat',
            old_name='avg_balance',
            new_name='avg_balance_after',
        ),
    ]
