# Generated by Django 3.2.4 on 2021-08-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0068_rename_avg_balance_roundstat_avg_balance_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='was_forced',
        ),
    ]
