# Generated by Django 3.2.4 on 2021-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0069_remove_trade_was_forced'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='was_forced',
            field=models.BooleanField(default=False),
        ),
    ]
