# Generated by Django 3.2.4 on 2021-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0070_trade_was_forced'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
