# Generated by Django 3.2.4 on 2021-08-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0071_trade_balance_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='balance_before',
        ),
    ]
