# Generated by Django 3.2.4 on 2021-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0073_roundstat_avg_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance_during_round',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
