# Generated by Django 3.2.4 on 2021-08-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0074_trade_balance_during_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='balance_during_round',
            new_name='balance_before',
        ),
    ]
