# Generated by Django 3.2.4 on 2021-09-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0058_auto_20210815_1138'),
        ('market', '0075_rename_balance_during_round_trade_balance_before'),
    ]

    operations = [
    ]
