# Generated by Django 3.2.6 on 2021-09-15 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0076_merge_20210902_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='max_rounds',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
