# Generated by Django 3.2.7 on 2021-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0077_alter_market_max_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='robot_game',
            field=models.BooleanField(default=False),
        ),
    ]
