# Generated by Django 3.2.7 on 2021-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0078_market_robot_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='allow_robots',
            field=models.BooleanField(default=False),
        ),
    ]
