# Generated by Django 3.2.7 on 2021-09-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0079_market_allow_robots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='robot_game',
        ),
    ]
