# Generated by Django 3.2.7 on 2021-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0080_remove_market_robot_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='auto_play',
            field=models.BooleanField(default=False),
        ),
    ]
