# Generated by Django 3.2.7 on 2021-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0081_trader_auto_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='removed_from_market',
            field=models.BooleanField(default=False),
        ),
    ]
