# Generated by Django 3.2.7 on 2021-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0081_trader_auto_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
