# Generated by Django 3.2.7 on 2021-10-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0082_market_deleted'),
        ('market', '0082_market_monitor_auto_pilot'),
    ]

    operations = [
    ]
