# Generated by Django 3.2.7 on 2021-10-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0082_trader_removed_from_market'),
        ('market', '0083_merge_20211008_1406'),
    ]

    operations = [
    ]
