# Generated by Django 3.2.7 on 2021-10-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0084_merge_20211008_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
