# Generated by Django 3.2.7 on 2021-10-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0085_alter_trader_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
