# Generated by Django 3.2.7 on 2021-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0086_trader_bankrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='game_over',
            field=models.BooleanField(default=True),
        ),
    ]
