BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBXXX XXBBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX gettext(u'LogIn') XXXXX
XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'LogIn') XXXXXXXXX
XXXXXXX
XXXX
XXX gettext(u'ForgotPassword')  XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'ResetPassword') XXXXXXXX
XXX gettext(u'HaveNoAccount')  XX XXXXXXBBB BBBBBBBBXX gettext(u'SignUp') XXXXXXXX

BBBBBBBB BBBBBBB
