BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBXXXX XXBBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX gettext(u'SignUp') XXXXX
XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'SignUp') XXXXXXXXX
XXXXXXX
BBBBBBBB BBBBBBB
