# Generated by Django 3.1.7 on 2021-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='round_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trader',
            name='round_price',
            field=models.IntegerField(default=0),
        ),
    ]
