# Generated by Django 3.1.7 on 2021-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_round_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='round_cost',
        ),
        migrations.AddField(
            model_name='trader',
            name='prod_cost',
            field=models.IntegerField(default=0),
        ),
    ]
