# Generated by Django 3.1.7 on 2021-04-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210415_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bank', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.trader')),
            ],
        ),
    ]
