# Generated by Django 3.2 on 2021-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210418_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='id',
        ),
        migrations.AlterField(
            model_name='market',
            name='market_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trader',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
